sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-secret: adEzPNF4U1tdbNAH7pdL4ycCeZyMqN
    bucket-name: black-sky
    access-key-id: LTAI5t5ZdmtYVQoqScBsMEug

